import arcade

game_table = [[arcade.color.BITTER_LIME,     arcade.color.CHROME_YELLOW,     arcade.color.BITTER_LIME,       arcade.color.CHROME_YELLOW,         arcade.color.BITTER_LIME,       arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW],
        [arcade.color.CHROME_YELLOW,    arcade.color.YELLOW,            arcade.color.BITTER_LIME,       arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,                arcade.color.BITTER_LIME,           arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,         arcade.color.BITTER_LIME],
        [arcade.color.BITTER_LIME,      arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,            arcade.color.YELLOW,                arcade.color.YELLOW,            arcade.color.CHROME_YELLOW,         arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,         arcade.color.YELLOW,                arcade.color.BITTER_LIME],
        [arcade.color.BITTER_LIME,      arcade.color.YELLOW,            arcade.color.CHROME_YELLOW,     arcade.color.BITTER_LIME,           arcade.color.YELLOW,            arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW,         arcade.color.BITTER_LIME,           arcade.color.BITTER_LIME,           arcade.color.YELLOW],
        [arcade.color.BITTER_LIME,      arcade.color.BITTER_LIME,       arcade.color.BITTER_LIME,       arcade.color.CHROME_YELLOW,         arcade.color.YELLOW,            arcade.color.YELLOW,                arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW],
        [arcade.color.CHROME_YELLOW,    arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,            arcade.color.CHROME_YELLOW,         arcade.color.YELLOW,            arcade.color.BITTER_LIME,           arcade.color.YELLOW,                arcade.color.YELLOW,                arcade.color.YELLOW,                arcade.color.BITTER_LIME],
        [arcade.color.CHROME_YELLOW,    arcade.color.BITTER_LIME,       arcade.color.BITTER_LIME,       arcade.color.BITTER_LIME,           arcade.color.BITTER_LIME,       arcade.color.YELLOW,                arcade.color.YELLOW,                arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW],
        [arcade.color.YELLOW,           arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,            arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,     arcade.color.CHROME_YELLOW,         arcade.color.BITTER_LIME,           arcade.color.BITTER_LIME,           arcade.color.YELLOW,                arcade.color.CHROME_YELLOW],
        [arcade.color.CHROME_YELLOW,    arcade.color.YELLOW,            arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,                arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,                arcade.color.BITTER_LIME,           arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,         arcade.color.CHROME_YELLOW],
        [arcade.color.CHROME_YELLOW,    arcade.color.BITTER_LIME,       arcade.color.YELLOW,            arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,     arcade.color.YELLOW,                arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,         arcade.color.YELLOW,                arcade.color.CHROME_YELLOW],
        [arcade.color.BITTER_LIME,      arcade.color.BITTER_LIME,       arcade.color.CHROME_YELLOW,     arcade.color.BITTER_LIME,           arcade.color.CHROME_YELLOW,     arcade.color.BITTER_LIME,           arcade.color.YELLOW,                arcade.color.BITTER_LIME,           arcade.color.YELLOW,                arcade.color.YELLOW]]
#                  1                              2                                   3                               4                                     5                                 6                                7                                          8                              9                                    10